// items.js

export const items = {
  rock: {
    name: "Rock",
    icon: "🪨",
    rarity: "Common",
    cost: 5,
    beats: ["scissors", "fire", "wind"],
  },
  paper: {
    name: "Paper",
    icon: "📄",
    rarity: "Common",
    cost: 5,
    beats: ["rock", "robot", "earth"],
  },
  scissors: {
    name: "Scissors",
    icon: "✂️",
    rarity: "Common",
    cost: 5,
    beats: ["paper", "water", "wind"],
  },
  fire: {
    name: "Fire",
    icon: "🔥",
    rarity: "Uncommon",
    cost: 10,
    beats: ["paper", "robot", "earth"],
  },
  water: {
    name: "Water",
    icon: "💧",
    rarity: "Uncommon",
    cost: 10,
    beats: ["rock", "fire", "dragon"],
  },
  robot: {
    name: "Robot",
    icon: "🤖",
    rarity: "Uncommon",
    cost: 12,
    beats: ["scissors", "water", "wizard"],
  },
  lightning: {
    name: "Lightning",
    icon: "⚡",
    rarity: "Rare",
    cost: 20,
    beats: ["fire", "dragon", "earth"],
  },
  wind: {
    name: "Wind",
    icon: "🌬️",
    rarity: "Rare",
    cost: 20,
    beats: ["paper", "earth", "wizard"],
  },
  earth: {
    name: "Earth",
    icon: "🌍",
    rarity: "Rare",
    cost: 20,
    beats: ["lightning", "robot", "dragon"],
  },
  wizard: {
    name: "Wizard",
    icon: "🧙",
    rarity: "Epic",
    cost: 40,
    beats: ["rock", "wind", "scissors"],
  },
  dragon: {
    name: "Dragon",
    icon: "🐉",
    rarity: "Epic",
    cost: 40,
    beats: ["wizard", "robot", "lightning"],
  },
  phoenix: {
    name: "Phoenix",
    icon: "� phoenix emoji 🔥",
    rarity: "Epic",
    cost: 45,
    beats: ["water", "earth", "robot"],
  },
  ninja: {
    name: "Ninja",
    icon: "🥷",
    rarity: "Legendary",
    cost: 75,
    beats: ["wizard", "dragon", "scissors"],
  },
  samurai: {
    name: "Samurai",
    icon: "🗡️",
    rarity: "Legendary",
    cost: 75,
    beats: ["ninja", "robot", "paper"],
  },
  alien: {
    name: "Alien",
    icon: "👽",
    rarity: "Legendary",
    cost: 80,
    beats: ["samurai", "phoenix", "fire"],
  },
  titan: {
    name: "Titan",
    icon: "🦾",
    rarity: "Mythic",
    cost: 120,
    beats: ["alien", "ninja", "wizard"],
  },
  vampire: {
    name: "Vampire",
    icon: "🧛",
    rarity: "Mythic",
    cost: 120,
    beats: ["samurai", "phoenix", "lightning"],
  },
  hydra: {
    name: "Hydra",
    icon: "🐍",
    rarity: "Mythic",
    cost: 120,
    beats: ["titan", "dragon", "wizard"],
  },
  mermaid: {
    name: "Mermaid",
    icon: "🧜",
    rarity: "Rare",
    cost: 25,
    beats: ["fire", "ninja", "earth"],
  },
  ghost: {
    name: "Ghost",
    icon: "👻",
    rarity: "Rare",
    cost: 25,
    beats: ["robot", "scissors", "titan"],
  },
  knight: {
    name: "Knight",
    icon: "🤺",
    rarity: "Epic",
    cost: 50,
    beats: ["vampire", "alien", "ghost"],
  },
  witch: {
    name: "Witch",
    icon: "🧙‍♀️",
    rarity: "Epic",
    cost: 50,
    beats: ["knight", "samurai", "ninja"],
  },
  angel: {
    name: "Angel",
    icon: "😇",
    rarity: "Mythic",
    cost: 150,
    beats: ["hydra", "vampire", "ghost"],
  },
  demon: {
    name: "Demon",
    icon: "😈",
    rarity: "Mythic",
    cost: 150,
    beats: ["angel", "mermaid", "witch"],
  },
  golem: {
    name: "Golem",
    icon: "🪨🤖",
    rarity: "Legendary",
    cost: 70,
    beats: ["titan", "ghost", "dragon"],
  },
  samuraiCat: {
    name: "Samurai Cat",
    icon: "🐱🗡️",
    rarity: "Rare",
    cost: 30,
    beats: ["ninja", "robot", "witch"],
  },
};
